[package]
name = "ws-framer"
version = "0.1.0"
edition = "2021"

[lib]

[[example]]
name = "ws-framer-test"

[dependencies]
httparse = { version = "1.9.5", default-features = false, optional = true }
itoa = { version = "1.0.11", optional = true }
ws-framer-macros = { path = "./macros" }

[dev-dependencies]
rand = "0.8.5"
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.91"

[features]
default = ["http"]
http = ["dep:httparse", "dep:itoa"]
