[package]
name = "ws-framer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
httparse = "1.9.5"
rand = "0.8.5"
macros = { path = "./macros" }
