[package]
name = "ws-framer"
version = "0.1.0"
edition = "2021"

[lib]

[[example]]
name = "ws-framer-test"

[dependencies]
httparse = "1.9.5"
macros = { path = "./macros" }

[dev-dependencies]
rand = "0.8.5"
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.91"
